columns_with_nulls = [
    'school_locale',
    'test_requirements',
    'booksupply_cost',
    'pell_grant_rate',
    'sat_scores_overall_average',
    'act_scores_50th_percentile',
    'admission_rate_overall',
    'completion_rate_suppressed',
    'retention_rate_full_time',
    'federal_loan_rate',
    'cost_of_attendance',
    'avg_net_price_overall',
    'tuition_in_state',
    'tuition_out_of_state',
    'roomboard_offcampus',
    'roomboard_oncampus',
    'otherexpense_oncampus',
    'otherexpense_offcampus',
    'student_size',
    'student_demographics_men',
    'student_demographics_women',
    'faculty_demographics_men',
    'faculty_demographics_women',
    'grad_enrollment_12_month',
    'undergrad_enrollment_12_month'
]

columns_to_int = [
    'student_size',
    'school_locale',
    'online_only',
    'open_admissions_policy',
    'carnegie_basic',
    'sat_scores_overall_average',
    'act_scores_50th_percentile',
    'grad_enrollment_12_month',
    'undergrad_enrollment_12_month'
]
